image: registry-testing.kazan.atosworldline.com/sandbox/automate_update:latest  

stages:  
    - testing               
    - change_json       
                  

testing:
    stage: testing    
    script:
    - python36 /automate/main.py

change_json:     
    stage: change_json
    script:
    - echo "this is change json file section"
